const express = require('express')
const app = express();

var ba = require('beeradvocate-api');

const beers = 
["Allagash Sixteen Counties",
"Allagash Black",
"Allagash Hoppy Table Beer",
"Allagash Interlude",
"Allagash Saison",
"Allagash Curieux",
"Allagash White",
"Big Elm 413 Farmhouse",
"Big Elm American Lager",
"Big Elm IPA",
"Brooklyn Bel Air",
"Brooklyn Summer",
"Brooklyn Sorachi Ace",
"Brooklyn Lager",
"Cambridge Brewing Company Charles River",
"Cambridge Brewing Company Flower Child",
"Cambridge Brewing Company Obscured By Clouds",
"Cambridge Brewing Company Working Class Hero",
"Cisco Grey Lady",
"Cisco Gripah",
"Cisco Whale's Tail",
"Collective Arts Ransack the Universe",
"Foundation Afterglow",
"Foundation Burnisde",
"Foundation Venture",
"Hidden Cove Summer Ale",
"Ipswich 1620",
"Ipswich Ale",
"Ipswich Cranberry Beret",
"Ipswich Oatmeal Stout",
"Ipswich Pesky Pils",
"Ipswich Route 101",
"Ipswich Blueberry Shandy",
"Ipswich Route 1A",
"Kentucky Bourbon Barrel Ale",
"Kentucky Vanilla Barrel Cream Ale",
"Left Hand Milk Stout",
"Left Hand Milk Stout (NITRO)",
"Lefty's Chocolate Oatmeal Stout",
"Lefty's Golden Ale",
"Lefty's Graham Cracker Porter",
"Lefty's IPA",
"Lefty's Pottery Trail Ale",
"Magic Hat #9",
"Maine Beer Co Mean Old Tom (NITRO)",
"Maine Beer Co Peeper",
"New Belgium Fat Tire",
"New Belgium Hemperor",
"New Belgium Sour Saison",
"New Belgium Voodoo Ranger Imperial IPA",
"Ommegang Abbey Ale",
"Ommegang Hennepin",
"Ommegang Rosetta",
"Oskar Blues Dale's Pale Ale",
"Riverwalk IPA",
"Riverwalk Rustic Pils",
"Sierra Nevada Hazy Little Thing",
"Sierra Nevada Pale Ale",
"Six Point Alpenflo",
"Six Point Bengali Tiger",
"Six Point The Crisp",
"Six Point Lo Res",
"Smuttynose IPA",
"Smuttynose Summer IPA",
"Smuttynose Vunderbar Pils",
"Smuttynose Brown",
"Smuttynose Porter",
"Southern Tier 2X IPA",
"Southern Tier Nu Skool",
"Stone Arrogant Bastard",
"Stone Double Bastard 2016",
"Stone Delicious IPA",
"Stone Go To IPA",
"Stone Imperial Russian Stout",
"Stone IPA",
"Stone Woot Stout",
"Stone Xocoveza",
"Troegs Crimson Pistil",
"Troegs Dreamweaver",
"Troegs Hopback Amber",
"Troegs Perpetual IPA",
"Victory Prima Pils",
"Victory Summer Love",
"Von Trapp Vienna Lager",
"Wachusett Blueberry",
"Wachusett Green Monsta",
"Wachusett Wally",
"Wash Ashore Buddha",
"Wash Ashore Maya Mae",
"Woodstock Pig's Ear",
"Downeast Aloha Friday",
"Downeast Cranberry",
"Downeast Double Blend",
"Downeast Drier Side",
"Downeast Original",
"21st Amendment Back In Black IPA",
"22nd Amendment Baby Horse Quad",
"23rd Amendment Blood Orange Brew Free or Die IPA",
"24th Amendment Hop Crisis",
"25th Amendment Brew Free or Die! IPA",
"26th Amendment Hell or High Watermelon ",
"Anderson Valley Brewing Bourbon Barrel Aged Salted Caramel Porter",
"Anderson Valley Brewing Blood Orange Gose",
"Anderson Valley Brewing Briney Melon Gose",
"Anderson Valley Brewing Wild Turkey Bourbon Barrel Stout (NITRO)",
"Anderson Valley Brewing Framboise Rose Gose",
"Anderson Valley Brewing The Kimmie, The Yink, & The Holy Gose",
"Anderson Valley Brewing G & T Gose",
"Anderson Valley Brewing Hop Hyzer Ale",
"Anderson Valley Brewing Horse Tongue Brettanomyces Wheat",
"Anderson Valley Brewing Huge Arker Bourbon Barrel Imperial Stout",
"Anderson Valley Brewing Summer Solstice",
"Anderson Valley Brewing Summer Solstice (NITRO)",
"Anderson Valley Brewing Thribble Currant",
"Avery Brewing Amicita No. 47",
"Avery Brewing Apricot Sour",
"Avery Brewing Coconut Porter",
"Avery Brewing Czar Imperial Stout",
"Avery Brewing El Gose ",
"Avery Brewing Ellie's Brown Ale",
"Avery Brewing Ginger Sour",
"Avery Brewing Uncle Jacob's Bourbon Barrel Aged Stout",
"Avery Brewing Liliko'i Kepolo Belgian White Ale",
"Avery Brewing Mephistopheles",
"Avery Brewing Nutty Professor",
"Avery Brewing Raspberry Sour",
"Avery Brewing Real Peel",
"Avery Brewing Samaels Oak Aged Strong Ale",
"Avery Brewing Tequilacerbus No. 43",
"Avery Brewing Tangerine Quad",
"Avery Brewing Tweak",
"Avery Brewing Vanilla Bean Bourbon Barrel Aged Stout",
"Avery Brewing White Rascal Belgian White Ale",
"Bear Republic Brewing Hop Shovel IPA",
"Bear Republic Brewing Kompromat",
"Bear Republic Brewing Racer 5",
"Bear Republic Brewing Tartare Rouge Sour Red Ale",
"Bear Republic Brewing Tartare Berliner Weisse",
"Breakside Brewery IPA",
"Breakside Brewery Lunch Break India Session Ale",
"Brown's Brewing Co Cherry Raspberry Ale",
"Brown's Brewing Co Oatmeal Stout",
"Dark Horse Plead the 5th Imperial Stout",
"Down The Road Brewery Seventh Star IPA",
"Down The Road Brewery Dreamtime New England IPA",
"Down The Road Brewery Golden City New England IPA",
"Down The Road Brewery Patchwork Kilt Scottish Style Ale",
"Down The Road Brewery Pukwudgie Session IPA",
"Down The Road Brewery Undine Double IPA",
"Evil Genius #Adulting",
"Evil Genius Purple Monkey Dishwasher",
"Evil Genius Stacy's Mom",
"Gigantic Brewing Most Premium Russian Imperial Stout",
"Great Divide Brewing 22nd Anniversary Dark American Sour aged in red wine barrels",
"Great Divide Brewing Barrel Aged Hibernation Old Ale",
"Great Divide Brewing Barrel Aged Old Ruffian Barley Wine",
"Great Divide Brewing Chai Oak Aged Yeti Imperial Stout",
"Great Divide Brewing Chocolate Oak Aged Yeti Imperial Stout",
"Great Divide Brewing Colette Farmhouse Ale",
"Great Divide Brewing Mexican Chocolate Oak Aged Yeti Imperial Stout",
"Great Divide Brewing Nadia Kali Hibiscus Saison",
"Great Divide Brewing Strawberry Rhubarb Sour Ale",
"Great Divide Brewing Titan IPA",
"Great Divide Brewing Yeti Imperial Stout",
"Heretic Brewing Company Alternating Current",
"Heretic Brewing Company Chocolate Hazelnut Porter",
"Heretic Brewing Company Cherry Agony",
"Heretic Brewing Company Evil Cousin Imperial IPA",
"Heretic Brewing Company Evil Twin Red IPA",
"Heretic Brewing Company Lager",
"Heretic Brewing Company Petit Rouge Belgian Blonde with Hibiscus",
"Heretic Brewing Company Torment",
"Jack's Abby Brewery Barrel Aged Framinghammer",
"Jack's Abby Brewery Blood Orange Wheat Lager",
"Jack's Abby Brewery Calyptra Session IPL",
"Jack's Abby Brewery Cordon Rouge",
"Jack's Abby Brewery Cranberry Berliner",
"Jack's Abby Brewery Excess IPL",
"Jack's Abby Brewery Franconian Kraft",
"Jack's Abby Brewery Graham Cracker Barrel Aged Framinghammer",
"Jack's Abby Brewery Heavy Trommel Keller",
"Jack's Abby Brewery Hoponius Union IPL ",
"Jack's Abby Brewery House Lager",
"Jack's Abby Brewery Mass Rising",
"Jack's Abby Brewery Mole Bourbon Barrel Aged Framinghammer",
"Jack's Abby Brewery Post Shift Pilsner",
"Jack's Abby Brewery Private Rye",
"Jack's Abby Brewery Saxony Lager",
"Jack's Abby Brewery Sibling Maker",
"Jack's Abby Brewery Smoke and Dagger (Nitro)",
"Jack's Abby Brewery Smoke & Dagger",
"Jack's Abby Brewery Vanilla Bourbon Barrel Aged Framinghammer",
"Lord Hobo Brewing Angelica",
"Lord Hobo Brewing Boom Sauce ",
"Lord Hobo Brewing Consolation Prize",
"Lord Hobo Brewing Glorious Pale Ale",
"Lord Hobo Brewing Hobo Life            ",
"Lost Abbey Agave Maria â€“ Tequila Barrel Aged",
"Lost Abbey Barrel Aged Serpent Stout",
"Lost Abbey Carnevale",
"Lost Abbey Deliverance",
"Lost Abbey Devotion",
"Lost Abbey Judgement Day",
"Lost Abbey Santo Ron Diego",
"Lost Abbey Serpent Imperial Stout",
"Maui Imperial Coconut Porter",
"Melvin Brewing Company 2X4 Double IPA",
"Melvin Brewing Company Asterisk Imperial IPA",
"Melvin Brewing Company Hubert MPA",
"Melvin Brewing Company Melvin IPA",
"Mighty Squirrel Cosmic Distortion",
"Mighty Squirrel IPA",
"Mighty Squirrel Mocha Milk Stout",
"Mighty Squirrel Kiwi White Ale",
"Mother Earth Boo Koo Mosaic IPA",
"Mother Earth Kismet Nelson IPA",
"Mother Earth Power of Love",
"Mother Earth Quit Stalin",
"Mother Earth Sin Tax",
"Port Brewing Bourbon Barrel Aged Santa's Little Helper",
"Port Brewing Nelson The Greeter",
"Port Brewing Hop Freshner Series",
"Springdale Brigadeiro Breakfast Stout",
"Springdale Desert Solitaire",
"Springdale Ghost Species",
"Springdale Pearly Wit",
"Springdale Suspended Animation",
"Springdale Terroirdome",
"Stoneface Brewing Co Blip ",
"Stoneface Brewing Co Cherry Lime Berliner",
"Stoneface Brewing Co Full Blip",
"Stoneface Brewing Co Full Clip IPA",
"Stoneface Brewing Co IPA",
"Stoneface Brewing Co American Pale Ale",
"Stoneface Brewing Co Porter",
"Uinta Brewing Grapefruit Hop Nosh IPA",
"Uinta Brewing Hop Nosh IPA",
"Weyerbacher Brewing Last Chance IPA",
"Weyerbacher Brewing Cinnsanity",
"Weyerbacher Brewing Mean Squeeze",
"Weyerbacher Brewing Mellow Monks",
"Weyerbacher Brewing Merry Monks",
"Weyerbacher Brewing Sexy Mother Pucker",
"Weyerbacher Brewing Sunday Morning Imperial Stout",
"White Birch Brewing Berliner Weisse",
"Zero Gravity Bretthead",
"Zero Gravity Conehead",
"Zero Gravity Green Street Lager",
"Zero Gravity Little Wolf",
"Ace Cider Co Perry",
"Ace Cider Co Pineapple",
"Ace Cider Co Space Blood Orange",
"Citizen Cider The Dirty Mayor",
"Citizen Cider Lake Hopper",
"Citizen Cider Unified Press",
"Citizen Cider Wit's Up",
" Seattle Cider Co Basil Mint",
" Seattle Cider Co Berry Rose",
" Seattle Cider Co Dry",
" Seattle Cider Co Gin Botanical",
" Seattle Cider Co Gose",
" Seattle Cider Co Washington Heirloom",
" Seattle Cider Co Imperial Honey",
" Seattle Cider Co Semi Sweet",
" Seattle Cider Co Tangerine Turmeric",
"Stormalong Dry Hop",
"Stormalong Legendary Dry",
"Stormalong Mass Appeal",
"Ballast Point Sculpin IPA",
"Ballast Point Grapefruit Sculpin",
"Ballast Point Sour Wench",
"Ballast Point Aloha Sculpin",
"Baxter Hop Tryst",
"Baxter Ein Stein",
"Baxter Prost Secco",
"Black Hog Piglet DIPA",
"Boulevard Tank 7",
"Boulevard Jam Band",
"Boulevard Hibiscus Gose",
"Castle Island Big Ern DIPA",
"Castle Island Lager",
"Castle Island Jetty Sour",
"Castle Island Candlepin",
"Castle Island Keeper",
"Dogfish Head Dragons and Yum Yums",
"Dogfish Head Liquid Truth Serum",
"Dogfish Head Festina Peche",
"Dogfish Head Mixed Media Vino Esque Ale",
"Dogfish Head 60 Minute IPA",
"Dogfish Head 90 Minute IPA",
"Dogfish Head Namaste",
"Dogfish Head Sea Quench Ale",
"Dogfish Head Flesh and Blood",
"Dogfish Head India Brown Ale",
"Dogfish Head Palo Santo Maron",
"Dogfish Head 120 Minute IPA",
"Dogfish Head Wood Aged Bitches Brew",
"Dogfish Head Lupu-Luau",
"Fool proof Raincloud Porter",
"Moat Mountain Flavah of the Day IPA",
"Moat Mountain Call It a Day DIPA",
"Moat Mountain Imperial Stout",
"Narragansett Lager",
"Narragansett Del's Shandy",
"Newburyport Tall Buoy",
"Newburyport Plum Island Belgian White",
"Newburyport Greenhead IPA",
"Notch Dog n' Pony",
"Notch Zwickel",
"Notch Pils",
"Notch Left of the Dial",
"Otter Creek Backseat Berner",
"Otter Creek  Ella Hoppy Lager",
"Otter Creek Free Flow IPA",
"Otter Creek Summer",
"Otter Creek IPA",
"Peak Organic Fresh Cut",
"Peak Organic Happy Hour",
"Peak Organic The Juice",
"Peak Organic Super Juice",
"Rapscallion Blonde",
"Revolution Sun Crusher",
"Revolution Amarillo Hero",
"Revolution Galaxy Hero",
"Revolution Anti-Hero",
"Rhinegeist Press Tart",
"Rhinegeist Sabertooth",
"Rising Tide Maine Ale",
"Sam Adams  Summer Ale",
"Sam Adams  Specialty Coffee Black Lager",
"Sam Adams  Rebel IPA",
"Sam Adams  Rebel Grapefruit IPA",
"Sam Adams  Rebel Juiced IPA",
"Sam Adams  Boston Lager",
"Spencer Trappist Ale",
"Spencer Grapefruit IPA",
"Two Roads Road 2 Ruin",
"Two Roads Bergamonst",
"Two Roads Honeyspot IPA",
"Two Roads No Limits Hefe",
"Two Roads Worker's Comp Saison",
"Two Roads Lil Heaven Session IPA",
"Wormtown Be Hoppy",
"Wormtown Hopulence",
"Wormtown Spies Like US",
"Bantam Wunderkind",
"Bantam Buzzwig",
"Bantam Hibiscus",
"Bantam Rojo",
"Rhinegeist Cidergeist Bubbles",
"Far From The Tree Nova",
"Far From The Tree Patch",
"Far From The Tree Lei",
"Farmer Willie's Extra Ginger",
"Urban Farm Fermentory Kombucha Ginger",
"Urban Farm Fermentory Kombucha Blueberry",
"Urban Farm Fermentory Kombucha Tumeric"];

function beerCsvGenerator() {
	var finalResult = "";

	beers.forEach(function(beerName) {
	  ba.beerSearch(beerName, function(beerSearchResults) {
	    var beerList = eval(beerSearchResults);
	    beerList.forEach(function(beerResult) {
	      ba.beerPage(beerResult.beer_url, function(beerPageResult) {
	        var beerPage = eval(beerPageResult)[0];
	        var resultString = beerPage.brewery_name + "," + beerPage.beer_name + "," + beerPage.beer_style + "," + beerPage.beer_abv + "," + beerPage.ba_score +"," + beerPage.ratings;
	        finalResult.concat(resultString);
	        console.log(resultString);
	      });
	    });
	  });
	});

	return finalResult;
}

app.get('/', (req, res) => res.send(beerCsvGenerator()));

app.listen(3000, () => console.log('Example app listening on port 3000!'));

